{{- if .Values.spring.config }}
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "spring.fullname" . }}-config
  namespace: {{ .Release.Namespace | quote }}
  labels:
    app: {{ include "spring.name" . }}
    chart: {{ include "spring.chart" . }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
data:
  application.yaml: |
{{ toYaml .Values.spring.config.contents | indent 4  }}
{{- end }}