{{- $fullName := include "spring.fullname" . }}
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "spring.fullname" . }}
  namespace: {{ .Release.Namespace | quote }}
  labels:
    app: {{ include "spring.name" . }}
    chart: {{ include "spring.chart" . }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app: {{ include "spring.name" . }}
      release: {{ .Release.Name }}
  template:
    metadata:
      labels:
        app: {{ include "spring.name" . }}
        release: {{ .Release.Name }}
      annotations:
        {{ toYaml .Values.podAnnotations | indent 8 }}
    spec:
      serviceAccountName: {{ template "spring.serviceAccountName" . }}
      securityContext:
        {{ toYaml .Values.securityContext | indent 8 }}
      containers:
        - name: {{ .Chart.Name }}
          {{- if .Values.container.debug.shellAtStartup }}
          command: ["/bin/sh"]
          args: ["-c", "while true; do echo hello; sleep 10;done"]
          {{- end }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          env:
            {{- if hasKey .Values.spring "debug" }}
            - name: debug
              value: {{ .Values.spring.debug | quote }}
            {{- end }}
            {{- if hasKey .Values.spring "profile" }}
            - name: SPRING_PROFILES_ACTIVE
              value: {{ .Values.spring.profile }}
            {{- end }}
            {{- if .Values.spring.trustKubernetesCertificates }}
            - name: KUBERNETES_TRUST_CERTIFICATES
              value: "true"
            {{- end }}
            {{- if .Values.secrets }}
            - name: SPRING_CONFIG_ADDITIONAL_LOCATION
              value: "file:/etc/springboot/secret"
            {{- end }}
            {{- range $key, $value := .Values.extraEnv }}
            - name: {{ $key }}
              value: {{ $value | quote }}
            {{- end }}
          volumeMounts:
            - name: data
              mountPath: /data
            - name: config-file
              mountPath: /config
            {{- if .Values.secrets }}
            - name: secrets
              mountPath: /etc/springboot/secret
            {{- end }}
          ports:
            - name: http
              containerPort: {{ .Values.containerPort }}
              protocol: TCP
          {{- if .Values.liveness.enabled }}
          livenessProbe:
{{ toYaml .Values.liveness.probe | indent 12 }}
          {{- end }}
          {{- if .Values.readiness.enabled }}
          readinessProbe:
{{ toYaml .Values.readiness.probe | indent 12 }}
          {{- end }}
          resources:
{{ toYaml .Values.resources | indent 12 }}
    {{- with .Values.nodeSelector }}
      nodeSelector:
{{ toYaml . | indent 8 }}
    {{- end }}
    {{- with .Values.affinity }}
      affinity:
{{ toYaml . | indent 8 }}
    {{- end }}
    {{- with .Values.tolerations }}
      tolerations:
{{ toYaml . | indent 8 }}
    {{- end }}
      volumes:
        - name: data
          emptyDir: {}
        - name: config-file
          configMap:
            name: {{ include "spring.fullname" . }}-config
        {{- if .Values.secrets }}
        - name: secrets
          projected:
            sources:
            {{- range .Values.secrets.names }}
            - secret:
                secretName: {{ . }}
            {{- end }}
        {{- end }}