{{- if .Values.ingress.enabled -}}
{{- $fullName := include "spring.fullname" . }}
{{- $httpPort := .Values.service.httpPort }}
apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  annotations:
  {{- range $key, $value := .Values.ingress.annotations }}
    {{ $key }}: {{ $value | quote }}
  {{- end }}
  labels:
    app: {{ template "spring.name" . }}
    heritage: "{{ .Release.Service }}"
    release: "{{ .Release.Name }}"
    chart: "{{ .Chart.Name }}-{{ .Chart.Version }}"
  name: {{ template "spring.fullname" . }}
  namespace: {{ .Release.Namespace | quote }}
spec:
  rules:
    - host: {{ template "spring.name" . }}-{{ .Release.Namespace }}.{{ .Values.ingress.dnswildcard }}
      http:
        paths:
          - path: /
            backend:
              serviceName: {{ $fullName }}
              servicePort: {{ $httpPort }}
  tls:
    - hosts:
        - {{ template "spring.name" . }}-{{ .Release.Namespace }}.{{ .Values.ingress.dnswildcard }}
      secretName: {{ template "spring.name" . }}-ingress-secret
{{- end -}}